[SQL]
HOST = localhost
PORT = 3306
USER = 
PASS = 
DB = 
CHARSET = utf8

[SSL]
CERTFILE = 
KEYFILE = 
PASS = 

[RUN]
ENABLESQL = False
ENABLESSL = False
HOST = 0.0.0.0
PORT = 3333

[DEBUG]
; CRITICAL=5 | ERROR=4 | WARNING=3 | INFO=2 | DEBUG=1 | NOTSET=0
LOGLEVEL = 3
