[SQL]
HOST = localhost
PORT = 3306
USER = 
PASS = 
DB = 
CHARSET = utf8

[RUN]
ATTENDANCE_INTERVAL = 30
POSITION_INTERVAL = 30

[DEBUG]
; CRITICAL=5 | ERROR=4 | WARNING=3 | INFO=2 | DEBUG=1 | NOTSET=0
LOGLEVEL = 3
