spring.main.allow-bean-definition-overriding=true
server.address=0.0.0.0
# API ȣ���, SQL ���� �ֿܼ� ����Ѵ�.
spring.jpa.show-sql=true
# DDL ���ǽ� �����ͺ��̽��� ���� ����� ����մϴ�.
# ex) ���̺� ����, ���� ��
spring.jpa.generate-ddl=true
# MySQL �� ����� ��.
spring.jpa.database=mysql
# MySQL �� ����
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.session.jdbc.initialize-schema: always
# DB ����
spring.datasource.url=#insert your db url here#
spring.datasource.username=#insert your username here#
spring.datasource.password=#insert your password here#
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
# ������ �� ��Ʈ ����
#server.ssl.enabled=true
#server.ssl.key-store=#insert your key store here#
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=#insert your password here
#server.port=443
server.port=8088